version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: flask_sample
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-net
  flask:
    build: ./flask
    ports:
      - "5000:80"
    volumes:
      - ./app:/usr/src/app
    command: flask run -h 0.0.0.0 -p 80
    networks:
      - app-net
    depends_on:
      - db
networks:
  app-net:
    driver: bridge